### ISSUE TITLE
Streaming: no audio

### ISSUE THREAD

**Issue by SabreWolfy** [abarisain/dmix#135]
I run mpd 0.17.1 and have MPDroid 1.03.1 running on a Samsung Galaxy S3 with Android ICS 4.0.4. Using MPDroid to control audio on the server works fine.

However, streaming does not. I have confirmed that streaming is working from mpd -- I can stream via Firefox and via mplayer successfully. When I try to stream from mpd, it shows that it is playing, but the volume always defaults to zero. Even when I move the volume slider up, I hear nothing, but the progress bar is moving and the seconds are counting up.

Sometimes MPDroid plays half a second of streaming music once or twice, but that is all -- the rest of the time it is silent while streaming.

Issue #129 mentions streaming not working after updating to 4.0, but I don't know what has been updated to "4.0" and the issue I have looks different to that.

**Comment by laplasz** [comment]
I have Galaxy S4 I9505 with stock 5.0.1 - everything is working except the streaming.. tried the lame encoder - without success. there is no error in the mpd log file.. any suggestion?
