### ISSUE TITLE
[Wishlist] Configurable buffer size for streaming audio

### ISSUE THREAD

**Issue by gigawatts** [abarisain/dmix#176]
Would be nice to be able to set the buffer size for streaming audio in the mpdroid app, as 20+ seconds seems kind of extreme.

Ideas include either a  "High, Medium, Low" buffer size, or preferably an option for "seconds/milliseconds of buffer size"

**Comment by bertiebaggio** [comment]
Commenting on an old, closed issue notwithstanding- VLC for Android permits setting a 'network caching' value; which suggests this feature is possible without root access. Or have I misunderstood?

**Comment by abarisain** [comment]
VLC does not use native Android libs but their own decoder.

I don't wish to do that, it's a lot of work.
