### ISSUE TITLE
single repeat mode

### ISSUE THREAD

**Issue by ajs124** [abarisain/dmix#188]
I think enabling repeat in mpdroid enables repeating the playlist at the moment.
Since I like to listen to songs over and over but don't want to change my playlist, I'd like to have a "single repeat mode" implemented.
Few mpd clients I tested in the past support this, but I know it is possible, for example if you turn on repeat and single in ncmpcpp (but it requires >=mpd-0.15_alpha\* according to the NEWS file in their source).
I looked at the [protocol reference](http://mpd.wikia.com/wiki/Protocol_Reference) but didn't find anything in it about the single mode.
I may be able to implement this and send a pull request, but I'm busy and unfamiliar with the codebase, but just in case noone wants to do this and I have enough time in the future.
UI wise I thought about something "spinning" through no repeat → repeat all → single repeat → …

**Comment by ajs124** [comment]
So, it's been a few years and I'm thinking about implementing this myself again.
Which branch should I develop something like this against?

**Comment by abarisain** [comment]
Develop. You'll also need some icons

**Comment by hurzl** [comment]
And what is the Single Mode in "master"?

**Comment by abarisain** [comment]
Single mode stops after the current songs finishes playing

**Comment by hurzl** [comment]
For me with "Repeat" it repeats a single track.

**Comment by abarisain** [comment]
You are right, it does. Never thought of combining both.

**Comment by ajs124** [comment]
I know about that, and I've used that until now, but I don't like the interface.

Single repeat is actually just turning on single mode and repeat mode, so the backend is already there.

**Comment by abarisain** [comment]
I understand. As long as the icon you will use is free, has dark/light mode, it's fine for me.
