### ISSUE TITLE
Support HTTP Basic auth on http streaming

### ISSUE THREAD

**Issue by tremby** [abarisain/dmix#219]
I don't particularly want my music stream from MPD to be accessible to the world (especially since that might criminalize me given that I'd be distributing copyrighted music) so I've set up Apache to use MPD's httpd stream (available just to localhost) reverse proxied and made available with HTTP Basic authentication to the internet at large. In case that sounds good to anyone else, the mpd.conf bit looks like

```
audio_output {
	type		"httpd"
	name		"Mono HTTP Stream q3"
	encoder		"vorbis"
	port		"6731"
	quality		"3.0"
	format		"44100:16:1"
	bind_to_address		"localhost"
}
audio_output {
	type		"httpd"
	name		"Stereo HTTP Stream q3"
	encoder		"vorbis"
	port		"6732"
	quality		"3.0"
	format		"44100:16:2"
	bind_to_address		"localhost"
}
```
(and another one for a slightly higher quality stream)

Then in my Apache config I have (in the default host)

```
	ProxyRequests off
	<Location /mpd/>
		AuthType Basic
		AuthName "MPD streams"
		AuthUserFile /var/www/.htpasswords
		Require valid-user
	</Location>
	ProxyPass /mpd/monoq3.ogg http://localhost:6731
	ProxyPassReverse /mpd/monoq3.ogg http://localhost:6731
	ProxyPass /mpd/stereoq3.ogg http://localhost:6732
	ProxyPassReverse /mpd/stereoq3.ogg http://localhost:6732
```

That works: I can listen to that from anywhere with for instance `mplayer -user tremby -passwd abc123 http://example.com/mpd/monoq3.ogg`

But MPDroid doesn't like it, since it is getting 401 unauthorized responses which presumably it doesn't understand and just ignores, retrying.

It'd be great if options for HTTP Basic auth username and password could be added.

I'd also love there to be multiple configurable streams to choose from (like in this case here, I just want mono when playing through the speaker but stereo as soon as I plug in headphones), but I guess that's a separate feature request.

**Comment by avuton** [comment]
Fixed via c5a376ff.

**Comment by tremby** [comment]
@avuton, where is that commit? It doesn't look like it's in this repository.

**Comment by avuton** [comment]
@tremby the final commit on the develop branch

**Comment by tremby** [comment]
Weird that it doesn't link it... Oh, you miscopied the hash! c5a376f0

**Comment by avuton** [comment]
Strange. Did it from my phone. Anything's possible! :)

**Comment by ChaoticMind** [comment]
@avuton it's the correct hash, just with an extra 'f'. Looks like github only makes it into a url if it's the "right" amount of prefix characters. This also applies to the other recent comments referencing the commit.

**Comment by tremby** [comment]
The next character should have been a 0, not an f, and pretty sure Github would recognize it: c5a376f0. Anyway, this is all moot now!
