### ISSUE TITLE
NetworkOnMainThreadException when long-pressing on entries in the database

### ISSUE THREAD

**Issue by craftyjon** [abarisain/dmix#283]
Bug report including stack trace being sent through Google Play.

Basically, the app somehow got into a state where any long-press (i.e. call to onCreateContextMenu() in BrowseFragment.java) would cause a NOMTE via the call to getPlaylists().  Unfortunately, my extent of Android/Java knowledge currently ends here so I cannot offer a proposed fix yet, but maybe I will try someday...

**Comment by avuton** [comment]
Fixed via 7232088.
