### ISSUE TITLE
Album cover from GraceNote

### ISSUE THREAD

**Issue by jcnoir** [abarisain/dmix#405]
There is an issue with cover fetching from gracenote.
In the free version you have a request quota. MPDroid popularity seems to exceed this quota ...
Since this provider is one of the last to be asked for a cover I thought it would be enough but I was wrong.
I asked to GraceNote if they can do something to help a free application. No answer yet.
I guess we may have to remove this provider. Too bad it gives good results for hard to find covers ...

**Comment by avuton** [comment]
Original bug has long been fixed. If something else is necessary it needs it's own issue.
