### ISSUE TITLE
count of MPDAsyncHelper.asyncExecListeners increment without decrement

### ISSUE THREAD

**Issue by chatminou** [abarisain/dmix#445]
Sorry for my poor english !

In BrowseFragment, when execute  :
app.oMPDAsyncHelper.addAsyncExecListener(this);
        iJobID = app.oMPDAsyncHelper.execAsync(new Runnable() {

you add a object in MPDAsyncHelper.asyncExecListeners.
When the asyn call is terminated, you receive a event EVENT_EXECASYNCFINISHED and loop on listeners to call asyncExecSucceeded.
The listener whth the good idJob do his task and NO ONE remove the listener from the MPDAsyncHelper.asyncExecListeners.

I propose do change in MPDAsyncHelper.java : 

public interface AsyncExecListener 
{
    public boolean asyncExecSucceeded(int jobID);
}

....

case EVENT_EXECASYNCFINISHED:
    AsyncExecListener listenerToRemove = null;
    for (AsyncExecListener listener : asyncExecListeners) {	
        if (listener == null) continue
        if (listener.asyncExecSucceeded(msg.arg1)) {
            listenerToRemove = listener;
            break;
        }
     }
     if (listenerToRemove != null) removeAsyncExecListener(listenerToRemove);
     break;

and change in BrowseFragment.java : 

@Override
 public boolean asyncExecSucceeded(int jobID) 
 {
    if (iJobID == jobID) {
        ....
        return true;
    }
    return false;
}

**Comment by avuton** [comment]
Obsoleted by d33ca48. Thanks for the report!
