### ISSUE TITLE
[1.07 Beta 4] Issue when browsing files

### ISSUE THREAD

**Issue by rripio** [abarisain/dmix#490]
Hello,

I'm having the following problem. When browsing thr library by "files", and going back in the directory hierarchy pressing [..], the upper menu, indicating "files" turns to show the current directory. The consequence is that switching to other mode of browsing is impossible, except iniciating the library browsing again with the top left menu.

No problem when going back in the directory tree with the back key, instead of [..].

Device: Xperia L, Android 4.2.2.

Thanks,

Roberto

**Comment by abarisain** [comment]
Think I fixed this already.
