### ISSUE TITLE
Strange behaviour for tracks with multi-artist-tags

### ISSUE THREAD

**Issue by MPconta** [abarisain/dmix#621]
Hello there,
some time ago a opened a VERY long and headache causing thread with the same topic. I hope you have already forgotten it... :-)

Now everything seems clearer and can be brought down to a simple question:
Why does MPDroid double the entries for albums with multi-artist-tags?

For example:
I got 3 albums with "Hans Theessink" as artist and every one of these 3 albums has a different second artist. When i telnet the following phrase to MPD

list album artist "Hans Theessink"

it gives me the 3 correct albums.

But when i search in MPDroid in the specific genre for "Hans Theessink", i get the albums doubled - i have 6 results, 2 for every album (incl. coverart). One of these doubled entries points to the correct album and the other one points to nirvana.

So, do you know what's the reason for this behaviour? And is it possible to change that?

**Comment by baloe** [comment]
Oh boy this is really a bummer. I have tons of albums with multiple album artists. Consider, for example, [Case / Lang / Veirs](https://www.discogs.com/master/1015198-Case-Lang-Veirs-Case-Lang-Veirs) by Laura Veirs, k.d. lang and Neko Case, who are three individual artists that made that one album together. This is what I get right now:

When browsing Neko Case's albums, the one album is listed three times, once for each album artist:  
![Albums by Neko Case](https://user-images.githubusercontent.com/12622691/209517015-856d9de9-697d-49ee-945d-cddb05e5d025.jpg)

and this is what I get when opening those three album tiles:
![Album tile for Laura Veirs](https://user-images.githubusercontent.com/12622691/209517341-8d8f29e4-5ae7-4e3b-b435-4da47aca35f2.jpg)
![Album tile for k.d. lang](https://user-images.githubusercontent.com/12622691/209517337-3d52c3a6-4af8-40f0-bec2-1918fd4b4d55.jpg)
![Album tile for Neko Case](https://user-images.githubusercontent.com/12622691/209517340-4c0188f1-2098-463b-beaa-d7fb46ea4bf9.jpg)

so, only the one associated with Laura Veirs shows the tracks, albeit then tagged with k.d. lang. It is so strange, and renders mpdroid almost useless for me.

**Comment by baloe** [comment]
please, reopen or I'll file a separate issue

**Comment by baloe** [comment]
> singularity in tags is pretty much a universal expectation.

I don't get it, so many Jazz albums are multi-album-artist albums. Take the albums recorded by [NDR Big Band](https://www.discogs.com/artist/503250-The-NDR-Big-Band), for example. They are almost always _NDR Big Band_ plus an invited collaborating artist.
