### ISSUE TITLE
Persistent notification gets stuck once in a while and lock screen control buttons disappear

### ISSUE THREAD

**Issue by martignlo** [abarisain/dmix#647]
I noticed several times (latest devel version, on two different devices) that the notification is not always properly updated (e.g., it mentions a song played in the past instead on the one currently playing). 

Furthermore, although I'm not sure the two issues are related, the cover and control buttons are not always present in the lock screen. That happens even when I lock the screen with the mpdroid app in foreground.

**Comment by avuton** [comment]
I have found a bug or two which probably resolves this, but, a release is still a bit away.

**Comment by avuton** [comment]
Going to consider this as fixed as it's going to be without a more specific bug. Things have gotten much better since this bug was created. Feedback (against the next Beta) is welcome.
