### ISSUE TITLE
Unable to connect - wifi connection showing not in range, even though connected

### ISSUE THREAD

**Issue by sach2** [abarisain/dmix#662]
## Issue
Unable to make connection. Possible reason could be that wifi connection is showing "not in range, remembered", even though it's connected.
The exact error is - Connection to MPD-server failed! Check if the server is running and reachable. (Failed initial connection.)

**Comment by MPconta** [comment]
I have the same problems with the Wlan-connection.
It seems, there is a "dirty" solution:
Minimize MPDroid and start Chrome. Immideately after starting, stop Chrome again and reenter MPDroid. --> It's working again.

So it looks like there is a possibility to wake the Wlan from some "sleep-modus" which is integrated in Chrome, but not in MPDroid.

**Comment by MPconta** [comment]
Is there no possibility to add the same wake-up-wlan-ability to MPDroid, like it is in Chrome?
It seems, the behavier of Android in this functionality has changed from 4.4 to 5.0?!

**Comment by avuton** [comment]
This issue should be fixed in the beta release.
