### ISSUE TITLE
MPDroid not pausing for phone call when not in memory.

### ISSUE THREAD

**Issue by thatarchguy** [abarisain/dmix#669]
MPDroid used to pause whenever I had an incoming phone call or made one.
It no longer does this, I even renabled the option in the settings.
Normal operations still work fine.

Samsung Galaxy S4  - > Music Player Daemon 0.19.6

**Comment by thatarchguy** [comment]
Hey I updated to the latest version in the play store and it's not pausing calls again, even while in memory.

I went back and installed that apk you linked me before and it's working fine.

**Comment by avuton** [comment]
Interesting. Don't think I changed the code, so, whatever works. Anyhow, there's some upstream stuff I'm working on right now which should make that code more dependable. After I'm done with that (1-2 months) I'll take a look at it.

**Comment by avuton** [comment]
@thatarchguy Finally getting around to working on this. Got a fix coming up in the next couple of days that, due to a new infrastructure, should fix it in a much more solid way.

**Comment by avuton** [comment]
@thatarchguy OK, finally got the commit in. Reviewed it quite a few times, tested over 50 times in many different scenarios. If you need a build, lemme know.

**Comment by Tigger2014** [comment]
Could I get a test build please, I've been having this issue aswell

**Comment by Tigger2014** [comment]
I've just compiled the dev branch after much of a fight with crashanlytics however the audio pause on calls is working great, I now can see any of my music in the app

**Comment by abarisain** [comment]
If you compile the foss flavour, crashlytics should not bother you






On Tue, May 12, 2015 at 10:31 AM -0700, "Ben Edmunds" <notifications@github.com> wrote:












I've just compiled the dev branch after much of a fight with crashanlytics however the audio pause on calls is working great, I now can see any of my music in the app

**Comment by Tigger2014** [comment]
Yeah i noticed that in the end. It seems to be working well. Except if im in a long call say 3mins + the music doesn't resume playing after

Sent from Yahoo Mail on Android

**Comment by avuton** [comment]
Time is not a differentiator. If you had a failure, you had one. I'll take a look at it sometime. It should be pretty reliable (it has been in my case) but YMMV and real life is kicking my ass right now.

**Comment by Tigger2014** [comment]
Oh i wasnt demanding you do anything, just thought i would let you know that's all. I'll keep those build for a while and see how it goes, it might actually be the app getting killed in the bsckground.

Sent from Yahoo Mail on Android
