### ISSUE TITLE
add support for variables in Tasker plugin

### ISSUE THREAD

**Issue by sanzoghenzo** [abarisain/dmix#672]
Hi,
first of all thanks for this great app!
I'm trying to use the tasker plugin to drive my morning alarm clock, and gently rise the volume, but currently your implementation doesn't let you set the volume based on a variable, so I can't use it in a loop (and adding something like 70 actions to only change the volume is not the way programming should work :) )
Variables could be useful also for #612 (which I also need to select the right playlist in the morning) to add some logic to the playlist loading.
Can you please add tasker variables support?

Thanks for the attention!

**Comment by abarisain** [comment]
Hello !

Please note that while MPDroid has a tasker plugin, I don't consider it reliable : Wifi can be off, connection might fail, and MPDroid is known to totally freeze when used a lot in tasker ...  

Anyway, I'm willing to dig into the implementation. I used tasker briefly, so I got how it works, but never used tasker variables. Can you give me a sample workflow that MPDroid could be compatible with, so that I can try ?

**Comment by abarisain** [comment]
By the way, the "set volume" action shows a popup before dismissing, allowing you to input a volume before returning to tasker, which should store the volume you set and give it back to MPDroid when it needs to execute the action.  

It's not a variable, but your workflow might work without variables ! (even if it's doesn't for playlists)

**Comment by sanzoghenzo** [comment]
Hi Arnaud, thanks for taking the time to review this.
I found that I can directly control my MPD (it's mopidy, so it has an http
interface) using jsonrpc calls via http post request in tasker, so I was
able to do what I wanted without your plugin.

My workflow consist in a loop that increases the volume with time (a gentle
alarm clock); without variables I should add 75 "set volume" actions (from
0 to 75, since I found it a good max volume level), one of each has a fixed
volume set.
Here's what's my workflow like (% its the symbol for variables):
1. set MPD volume to 0
2. MPD load a playlist (and optionally a MPD shuffle playlist to listen to
different songs sequence every morning)
3. MPD play
4. set variable %count to 1
5. while %count < 76
6. set MPD volume to %count
7. wait 10 seconds
8. add 1 to %count
9. go to action 5

But now that I think of it the set volume action would be the only one
benefitting from variable integration. And if it's only me, you can avoid
even thinking about coding it :P

**Comment by abarisain** [comment]
Thanks for your feedback. I'm closing this until somebody requests it again. To be honest, I think 5 people are using the tasker integration ;)  

Since it's mopidy you're running, jsonrpc is a MUCH better way to achieve that.
