### ISSUE TITLE
Scrollbar handle not usable when at top scroll position

### ISSUE THREAD

**Issue by stefan-girlich** [abarisain/dmix#686]
1. Go to library view, scroll bar handle is in top position
2. Try to scroll by dragging handle
3. Handle is not cannot be dragged, pull-to-refresh is triggered instead
4. Scroll down (distance doesn't seem to matter)
5. Scroll bar handle can be dragged now

Seen on MPDroid 1.07.2 Final ba27ds2a-c (54), Android 5.0.1

**Comment by abarisain** [comment]
Will be fixed in material redesign : pull to refresh is gone
Le mar. 20 janv. 2015 à 21:42, Stefan Girlich <notifications@github.com> a
écrit :

**Comment by abarisain** [comment]
Closed since pull to refresh is gone.
