### ISSUE TITLE
What about a notification ?

### ISSUE THREAD

**Issue by flyingrub** [abarisain/dmix#687]
A notification allow to quickly change music or play/pause music, on lockscreen or in any app.

And what about when we launch mpd, the volume button only control mpd, even if we are not on the app. (As long as we have the notification, wich mean a service running).

**Comment by abarisain** [comment]
We've got a notification already.

Hooking the volume keys outside of mpdroid is not something I'd like (qnd I don't think it can be done easily)

**Comment by flyingrub** [comment]
i have no notification actually running the latest version on the playstore.
And i don't understand why it would be more difficult than actually in the app ?

**Comment by avuton** [comment]
Persistent notification (semi-permanent) is an option in the settings, notification option is in the drop down menu. Now, if you're on Andoid 4.0.2 or less the notification won't be there (it's an old unsupported version).

Secondly, Android doesn't give the ability to use the volume keys willy nilly. We have to be in the foreground and not just a notification. This could change in the future with brand new API stuff, but most likely not. Not to mention abarisain and I are not motivated to implement such a thing.

**Comment by flyingrub** [comment]
i'm on android L on my nexus 5 and can't find any notification option in the settings, there isn't any dropdown menu.

**Comment by avuton** [comment]
OK, look under the connection settings (under wifi or default) and you'll see a checkbox there for persistent notification. Secondly, look at the Now Playing view where you see the big album art and the seek bar, and there's a drop down menu to the upper right. There should be a notification checkbox in there if you don't already have persistent notification enabled. If you can't find either of those, I suggest you look harder but there's really nothing further we can do to assist you here, they're both there.

**Comment by flyingrub** [comment]
If i didn't found it without explanation it's perhaps because it's designed in a wrong way.
( i just want to help the app to be better, no offense intended ;) )
