### ISSUE TITLE
can't connect to Mpd after update

### ISSUE THREAD

**Issue by andreainno** [abarisain/dmix#690]
Hi, i just update Mpdroid to the last version available, but it doesen't work: i can't connect.
When i launch the app it say: "Connection to MPD-Server failed! Ceck if the Server is running and reachable. (Failed initial connection)"
I ceck the server, and it is all ok, it work properly with old version of Mpdroid: the 1.06 is the latest that work fine for me :(

**Comment by avuton** [comment]
What version of MPD, what implementation (the one from musicpd.org?).

**Comment by avuton** [comment]
Also, do you use a password? If NOT, check the password box and, if it exists, remove the entry there (if I remember right, that's one of the ways to cause this bug).

**Comment by andreainno** [comment]
I can't see what version i am using because i can't log into GUI (because of the problem to access).
I use a password in Voyage so i think i need to set the passw in the MPdroid interface.

**Comment by avuton** [comment]
Aah, Voyage, an old embedded version of MPD, you're not the first to have problems logging into it, and I'm not really sure why yet. I'm going to start working on connection code soon, so give me a couple of days to try and bake something up and I'll hopefully have some test code for you to try.

**Comment by andreainno** [comment]
No problem, i will wait :)
Do you think there is something better than Voyage, to listen good quality Music?
Thanks!

**Comment by avuton** [comment]
Well, the stock implementation is technically the same if not better with regard to quality. I hope to upload a tester tonight or tomorrow.

**Comment by avuton** [comment]
OK, a lot of the connection code has been refactored, and I'm pretty hopeful that I will have something usable in the next week. I have one final bug to find before I'll feel comfortable having you test. This is just a notice that I haven't forgotten about you :+1:

**Comment by andreaea** [comment]
thank you man, don't worry, i know you are at work   ;)

**Comment by andreainno** [comment]
Ooops, i notice now that i post the previous reply as a different user, how it can happen?
I posted from smartphone.
Very strange...

**Comment by avuton** [comment]
OK, if you have time give [this apk](https://drive.google.com/file/d/0B1aD76XF-iKLSFhjMEFKSE9ISjQ/view?usp=sharing) a shot. It's ugly, it'll probably crash, it's alpha quality but I really want to know if I'm on the right track. To install it, you will be required to uninstall the previous version; if you choose to give this a shot, remember to restore your previous version.

**Comment by andreainno** [comment]
Hi Avuton.
I try the version you send me.
I launch the app, and i got no error message on log.
It takes to me several times to insert the data needed (host, password etc.), because the software crash a lot of times during this operation.
After i succeed to insert all the data needed, the software show me the main page (artists) interface but with "no result", and if i switch library view (between albums, genres, files etc.) i got the same result: "no result" (In the other version there was a option, the "refresh MPD database" button, to update).
The "Outputs" tab is empty, so i assume that the apps log into server, but can't retrieve the data from properly.
I hope it helps you.
Please fell free to ask if you need to know more: i got 2 smartphones, so i keep the version you send me, installed on one of these.

**Comment by avuton** [comment]
OK, well, it's going to take a couple of weeks for me to get it a bit more stable, we'll try again then. Thanks!

**Comment by avuton** [comment]
Well, this is shameful. I'm still pretty hopeful that I can find the problem (I'm going to /try/ to get VoyageMPD running in a VM) but I just tested each version back to 0.15 and, other than expected missing error handling I had no issues. Trying to get VoyageMPD running in a VM is a HUGE waste of time. Which version of Voyage are you running.

**Comment by avuton** [comment]
OK, I've got it running on VoyageMPD's live CD 0.9.5 without issue. There should be /some/ errors popping up in the logs (for you), but I really don't have time to deal with that right now, as I have quite a ways to go to get this stabilized in the first place. Also, it kinda goes without saying that, for right now, MPDroid /must/ be killed after configuration and before running. That's the part of the error handling that I have yet to fix.

**Comment by andreainno** [comment]
Hi Avuton, the version of Voyage on my PC is 0.9.2

**Comment by avuton** [comment]
Yep, just ran the 0.9.2 live CD as well, no problems here. I guess we'll see what happens in a couple of weeks (or months?) when I get some of these error handling bugs shook out.

**Comment by avuton** [comment]
This must be fixed at this point. Otherwise, something way beyond our control is going on here, and I'm going to need much more information, like a logcat. Please reopen with more information if this problem persists with the last beta.
