### ISSUE TITLE
No album art under Albums view?

### ISSUE THREAD

**Issue by PureW** [abarisain/dmix#692]
Hello there, I'm running mpdroid 1.07.2 Final on my Nexus 5 and mpd 0.18.7 on my htpc.

In mpdroid, I see album art when sorting library on artists and clicking on an artist, and also under the Now Playing view. (I have no album covers in the file library so I assume mpdroid fetches these album covers from the web, based artist/album tags).

However, under the Album view, I see no album covers, just the placeholder sound note which makes me sad :( Why is this? The album view would be beautiful with the album covers there.

**Comment by avuton** [comment]
Wow, sorry to hear it, but, the way support for that feature was added only works with MPD 0.19.x and above, but once you update your server it will work(!) I'm rather doubtful it could have been efficiently added without the particular MPD feature that was added in MPD 0.19.x.

Please feel free to add to this bug, but I'm going to close it as I consider this resolved, but I will continue watching it in case there is anything else I can do here.

**Comment by PureW** [comment]
Update: I compiled 0.19.8 from source and now the album art works perfectly!
