### ISSUE TITLE
Context menu glitch when adding items to playlist

### ISSUE THREAD

**Issue by comiconomenclaturist** [abarisain/dmix#695]
I have an issue with MPDroid 1.0.7 on my Android 4.1.1 Sony Xperia E when adding items from the library to the playlist. Sometimes the context menu displays correctly but often the screen is completely garbled and illegible. Pressing on where I think the relevant button is located seems to work, ie Add Artist is at the top.

**Comment by comiconomenclaturist** [comment]
![screenshot_2015-02-11-11-43-34](https://cloud.githubusercontent.com/assets/4951030/6146699/5bc2fa26-b1e7-11e4-8598-2b2dd3842d54.png)

**Comment by abarisain** [comment]
Oh wow.  

I'm sorry though, but I doubt I can fix the problem myself. The popup is a standard android popup menu, and it appears that your phone really doesn't like it

**Comment by comiconomenclaturist** [comment]
Hmmm, that's a shame. Thanks for an amazing app anyway, I will continue using it regardless of this issue!

**Comment by abarisain** [comment]
Closing, since we'll probably never get a satisfying answer. Lets hope that new releases will not have that problem for you, sorry :(
