### ISSUE TITLE
Allow the user to hide the volume slider

### ISSUE THREAD

**Issue by rompolompo** [abarisain/dmix#700]
I don't use MPD to control the volume (my preamp does it) and the volume slider has no use for me. Also, sliding it right and left does nothing as MPD send bit perfect data to my DAC.

An option to hide the volume slider would be nice to have.

**Comment by avuton** [comment]
This functionality already exists. If MPD reports a volume of -1 to us, the
slider should hide.

On Tue, Feb 17, 2015 at 10:17 AM, rompolompo <notifications@github.com>
wrote:

> I don't use MPD to control the volume (my preamp does it) and the volume
> slider has no use for me. Also, sliding it right and left does nothing as
> MPD send bit perfect data to my DAC.
>
> An option to hide the volume slider would be nice to have.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/abarisain/dmix/issues/700>.
>



-- 
avuton
--
Fortes fortuna adiuvat

**Comment by rompolompo** [comment]
Then this is a bug.

**Comment by avuton** [comment]
Please send the response to the status command from your MPD server.

On Tue, Feb 17, 2015 at 12:00 PM, rompolompo <notifications@github.com>
wrote:

> Then this is a bug.
>
> On Tue, Feb 17, 2015 at 2:56 PM, Avuton Olrich <notifications@github.com>
> wrote:
>
> > This functionality already exists. If MPD reports a volume of -1 to us,
> the
> > slider should hide.
> >
> > On Tue, Feb 17, 2015 at 10:17 AM, rompolompo <notifications@github.com>
> > wrote:
> >
> > > I don't use MPD to control the volume (my preamp does it) and the
> volume
> > > slider has no use for me. Also, sliding it right and left does nothing
> as
> > > MPD send bit perfect data to my DAC.
> > >
> > > An option to hide the volume slider would be nice to have.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/abarisain/dmix/issues/700>.
> > >
> >
> >
> >
> > --
> > avuton
> > --
> > Fortes fortuna adiuvat
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/abarisain/dmix/issues/700#issuecomment-74740275>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/abarisain/dmix/issues/700#issuecomment-74740920>.
>



-- 
avuton
--
Fortes fortuna adiuvat

**Comment by avuton** [comment]
Also, which version?

On Tue, Feb 17, 2015 at 12:03 PM, Avuton Olrich <avuton@gmail.com> wrote:

> Please send the response to the status command from your MPD server.
>
> On Tue, Feb 17, 2015 at 12:00 PM, rompolompo <notifications@github.com>
> wrote:
>
>> Then this is a bug.
>>
>> On Tue, Feb 17, 2015 at 2:56 PM, Avuton Olrich <notifications@github.com>
>> wrote:
>>
>> > This functionality already exists. If MPD reports a volume of -1 to us,
>> the
>> > slider should hide.
>> >
>> > On Tue, Feb 17, 2015 at 10:17 AM, rompolompo <notifications@github.com>
>> > wrote:
>> >
>> > > I don't use MPD to control the volume (my preamp does it) and the
>> volume
>> > > slider has no use for me. Also, sliding it right and left does
>> nothing as
>> > > MPD send bit perfect data to my DAC.
>> > >
>> > > An option to hide the volume slider would be nice to have.
>> > >
>> > > —
>> > > Reply to this email directly or view it on GitHub
>> > > <https://github.com/abarisain/dmix/issues/700>.
>> > >
>> >
>> >
>> >
>> > --
>> > avuton
>> > --
>> > Fortes fortuna adiuvat
>> >
>> > —
>> > Reply to this email directly or view it on GitHub
>> > <https://github.com/abarisain/dmix/issues/700#issuecomment-74740275>.
>>
>> >
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/abarisain/dmix/issues/700#issuecomment-74740920>.
>>
>
>
>
> --
> avuton
> --
> Fortes fortuna adiuvat
>



-- 
avuton
--
Fortes fortuna adiuvat

**Comment by rompolompo** [comment]
Let me update to the latest. I am currently running 0.19.4.....

**Comment by avuton** [comment]
Actually, I need the MPDroid version, also the status response.

On Tue, Feb 17, 2015 at 12:07 PM, rompolompo <notifications@github.com>
wrote:

> Let me update to the latest. I am currently running 0.19.4.....
>
> On Tue, Feb 17, 2015 at 3:05 PM, Avuton Olrich <notifications@github.com>
> wrote:
>
> > Also, which version?
> >
> >
> > On Tue, Feb 17, 2015 at 12:03 PM, Avuton Olrich <avuton@gmail.com>
> wrote:
> >
> > > Please send the response to the status command from your MPD server.
> > >
> > > On Tue, Feb 17, 2015 at 12:00 PM, rompolompo <notifications@github.com
> >
> > > wrote:
> > >
> > >> Then this is a bug.
> > >>
> > >> On Tue, Feb 17, 2015 at 2:56 PM, Avuton Olrich <
> > notifications@github.com>
> > >> wrote:
> > >>
> > >> > This functionality already exists. If MPD reports a volume of -1 to
> > us,
> > >> the
> > >> > slider should hide.
> > >> >
> > >> > On Tue, Feb 17, 2015 at 10:17 AM, rompolompo <
> > notifications@github.com>
> > >> > wrote:
> > >> >
> > >> > > I don't use MPD to control the volume (my preamp does it) and the
> > >> volume
> > >> > > slider has no use for me. Also, sliding it right and left does
> > >> nothing as
> > >> > > MPD send bit perfect data to my DAC.
> > >> > >
> > >> > > An option to hide the volume slider would be nice to have.
> > >> > >
> > >> > > —
> > >> > > Reply to this email directly or view it on GitHub
> > >> > > <https://github.com/abarisain/dmix/issues/700>.
> > >> > >
> > >> >
> > >> >
> > >> >
> > >> > --
> > >> > avuton
> > >> > --
> > >> > Fortes fortuna adiuvat
> > >> >
> > >> > —
> > >> > Reply to this email directly or view it on GitHub
> > >> > <https://github.com/abarisain/dmix/issues/700#issuecomment-74740275
> >.
> > >>
> > >> >
> > >>
> > >> —
> > >> Reply to this email directly or view it on GitHub
> > >> <https://github.com/abarisain/dmix/issues/700#issuecomment-74740920>.
> > >>
> > >
> > >
> > >
> > > --
> > > avuton
> > > --
> > > Fortes fortuna adiuvat
> > >
> >
> >
> >
> > --
> > avuton
> > --
> > Fortes fortuna adiuvat
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/abarisain/dmix/issues/700#issuecomment-74741760>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/abarisain/dmix/issues/700#issuecomment-74742147>.
>



-- 
avuton
--
Fortes fortuna adiuvat

**Comment by rompolompo** [comment]
Indeed. I just want to ensure I am running the latest version of MPD first.

**Comment by rompolompo** [comment]
Ha! You are right. No volume slider is shown. Was this feature dependent on
any recent MPD versions? I guess my memory is not what it used to be...

**Comment by rferguson10** [comment]
I'm using the latest version of MPD (0.21.13) and the latest MPDroid app and this doesn't seem to work any longer. 

It looks like they've removed the arbitrary -1 aspect of value reporting:

https://www.musicpd.org/doc/html/protocol.html

**Under Status:**

volume: 0-100 (deprecated: -1 if the volume cannot be determined)

"MPD may omit lines which have no (known) value. Older MPD versions used to have a “magic” value for “unknown”, e.g. “volume: -1”."

**Comment by abarisain** [comment]
Sorry, but MPDroid isn't under active development anymore.

I'm not sure why the author makes such breaking changes for no reason.
