### ISSUE TITLE
Library Loading takes very long 

### ISSUE THREAD

**Issue by gspatzenegger** [abarisain/dmix#702]
Coming from genre - artist loading the album library takes 45 seconds for 150 albums. In former versions it took only 1-2 seconds, without coverloading.

**Comment by avuton** [comment]
Hello,

I, actually, couldn't agree more. I'm working on improving performance (in many places it sucks). With all that said, I've already made vast improvements, many in the last week. BUT if it's taking 45 seconds for 150 albums, something's going terribly wrong and you're probably getting silent errors outputted in your logcat. Our error handling blows.. you can easily get errors and never know it! I'm busy working on that.

With that said, there are things I need and things you could do, but I'll be out of my development space for the next few days.

What I need:
What version of MPD are you using?
What implementation are you using (MPD? Mopidy?)
What device are you using?

What you can do to help figure this problem out:
* Run adb logcat during or after this library load. You'll likely see some interesting stuff there. Feel free to upload it (or a link to the log itself) here, especially if there's some interesting stuff in it.

If your device is running Android 5 or greater, you could easily [make a test build](https://github.com/abarisain/dmix/wiki/Building-on-the-Command-Line) from the latest sources to see if we've cleared up your pain point. Right now, we're Android 5 only, but that will (hopefully) change in the not so distant future.

**Comment by hurzl** [comment]
It can only take 45 sec. if you use the album cache and it has to be rebuilt (after library change) and you have a _huge_ library, a slow network and a slow server ...

**Comment by gspatzenegger** [comment]
Hello,
thank you for your reply.
I installed MPDroid on a Moto G 2nd generation with 5.0.2, Moto X 1st
generation with 4.4.2, Lenovo with 4.4.2 and a Nexus 7 2nd generation with
5.0.2. I am using MPD version 0.18 on a VUSolo2 receiver, my library
contains 36.000 files. The problem is the same on each of these devices. I
also installed an older version of MPDroid and the problem is gone.

Even if I turn of all coverloading options, MPDroid tries to load covers -
but I think this is not the reason for my problem, because I changed the
code and turned of coverloading this way. The problem persists.

Unfortunatly the logcat does not show any entries during library loading,
except for these ones:

02-28 19:44:50.368  31246-31246/com.namelessdev.mpdroid W/Resources﹕
Converting to string: TypedValue{t=0x4/d=0x3f800000 a=2 r=0x7f0c00e8}
02-28 19:44:50.411  31246-31246/com.namelessdev.mpdroid W/Resources﹕
Converting to string: TypedValue{t=0x4/d=0x3f800000 a=2 r=0x7f0c00e8}
02-28 19:44:54.763  31246-31246/com.namelessdev.mpdroid W/Resources﹕
Converting to string: TypedValue{t=0x4/d=0x3f800000 a=2 r=0x7f0c00e8}

I will install another MPD Server on my PC and see if library loading is
faster. Furthermore I will try the version from the link you sent me.
Thank you very much for your efforts!

Best regards
Günther

mfG
Günther Spatzenegger
Tel.: +43 664 2023161
mailto: g.spatzenegger@gmail.com

2015-02-28 14:35 GMT+01:00 Avuton Olrich <notifications@github.com>:

**Comment by gspatzenegger** [comment]
Hello again,
now I tried your beta version (it's great!) and I installed another MPD
with the same library on my PC.
With the MPD on my PC which is version 0.17 the loading takes only 3
seconds. The strange thing is, that the old version of mpdroid works
normally with the MPD 0.18 on my receiver (VUSolo2).

Best regards
Günther

mfG
Günther Spatzenegger
Tel.: +43 664 2023161
mailto: g.spatzenegger@gmail.com

2015-02-28 14:35 GMT+01:00 Avuton Olrich <notifications@github.com>:

**Comment by gspatzenegger** [comment]
Hello again,
the last one on this: I found out that the bottleneck is the MPD server. It
has 100% CPU utilization while albums are loaded. The difference between
the VUSolo2 and my PC is the performance - this is the reason why it
performs with the MPD on my PC. So it's not a bug in the app, although it
must have been different in previous versions of mpdroid, when the
performance of the VU was good enough.

Greetings  from vienna, Gue

mfG
Günther Spatzenegger
Tel.: +43 664 2023161
mailto: g.spatzenegger@gmail.com

2015-02-28 14:35 GMT+01:00 Avuton Olrich <notifications@github.com>:

**Comment by gspatzenegger** [comment]
You are partly right. My server is slow because it's a linux receiver. The
strange thing is, that the performance was good enough for the older
versions of MPDroid. By the way: caching doesn't work for local covers at
least on android 5.0.2, so I switched of the album cache. My library is
36000 files.

mfG
Günther Spatzenegger
Tel.: +43 664 2023161
mailto: g.spatzenegger@gmail.com

2015-02-28 15:04 GMT+01:00 hurzl <notifications@github.com>:

**Comment by hurzl** [comment]
I have no problem with 27000 files, the cache reload takes <10 sec.
Album cache has nothing to do with covers.
I don't know which versions of MPDroid you used, so it's hard to tell what the difference is.

**Comment by gspatzenegger** [comment]
The version I used is the one that you can find as "mupeace" app in the
playstore - it's a copy of mpdroid. I appreciate the new features & design
very much, so i don't want to go back to the old version. I don't know what
the difference is, but I assume that there are more mpd commands to process
than in the former version.

Thanks anyway for answering!

mfG
Günther Spatzenegger
Tel.: +43 664 2023161
mailto: g.spatzenegger@gmail.com

2015-02-28 23:15 GMT+01:00 hurzl <notifications@github.com>:

**Comment by hurzl** [comment]
I thought mupeace was a fork of an old MPDroid version. It doesn't even have an album cache at all ...

**Comment by avuton** [comment]
This issue is confusing and disjointed. There are conflicting things going on here, such as something about Mupeace, or Album Cache (nothing to do with albumcovers), or that MPD is the bottleneck. Between all this, I have no idea what's going on. Unless someone else takes this, if this issue is not going to be more clearly described, I'm going to suggest we close it (is it even still applicable??) and wait for a new, more detailed issue be opened.

**Comment by avuton** [comment]
OK, please reopen or start a new detailed issue that clearly explains the problem, if it still exists.
