### ISSUE TITLE
Disallow invalid port numbers.

### ISSUE THREAD

**Issue by avuton** [abarisain/dmix#705]
It should be set in the UI to disallow invalid port numbers as they'll crash MPDroid with a [IllegalArgumentException](https://github.com/abarisain/dmix/blob/master/JMPDComm/src/main/java/org/a0z/mpd/connection/MPDConnection.java#L145). This was disallowed in JMPDComm previously, this will be removed shortly and should be done by the client and UI.

**Comment by abarisain** [comment]
Users can modify the sharedpreferences at will though, so we might want a safeguard another place than simply on the UI.

**Comment by avuton** [comment]
I'll get this one.

**Comment by avuton** [comment]
Fixed via c5a376ff.
