### ISSUE TITLE
add a stop-button

### ISSUE THREAD

**Issue by mhellwig** [abarisain/dmix#708]
seriously, this is driving me up the wall .. I need a different, second (otherwise less feature-complete) mpd client installed just so that I can _stop_ (instead of pause). please please PLEASE add the stop-button.

**Comment by abarisain** [comment]
There is one in the UI settings.

**Comment by mhellwig** [comment]
huh. is this a new feature? Could have sworn I've been through these settings a hundred times ..

**Comment by abarisain** [comment]
Nah, it's been there for at least a year or two :) No problem though, that happens.

**Comment by abarisain** [comment]
Is it working allright ?

**Comment by mhellwig** [comment]
yep. does. sorry ..

**Comment by abarisain** [comment]
No problem!
