### ISSUE TITLE
Single tap behavior for streams in "Simple Mode"

### ISSUE THREAD

**Issue by Hollol** [abarisain/dmix#710]
The "Simple Mode" from current revision doesn't seem to work for me in streams: single tapping of a stream item adds to queue instead of playing. Holding and selecting "play" works though as expected. 
For playlists it is working as expected: single tap = direct play.

Is this a bug or a design decision for the streams section? 
A similar situation has been observed and corrected for playlists (see #565). 

Best regards,
Lars

**Comment by abarisain** [comment]
Probably an oversight

**Comment by Hollol** [comment]
Yesterday, I checked the behavior again. It is even worse than described in my previous post: Actually, nothing happens on single tapping an item in the stream list. That means the stream is even not added to the playlist.When long tapping a stream item, the option menu is popping up and streams can be added and/or played correctly.
Hopefully, this can be corrected in a next version, so that single taping in "simple mode" directly plays the stream. Thanks

**Comment by avuton** [comment]
I'll check it out today.

**Comment by Hollol** [comment]
Thanks

**Comment by avuton** [comment]
Fixed via 94b462b. Thanks for the report!
