### ISSUE TITLE
Remove artist under cover from artist library view

### ISSUE THREAD

**Issue by w-b-kelso** [abarisain/dmix#715]
In the artist library view the artist is shown under each cover. Hence most of the time you can't see the album year or the track quantity and the duration because the artist name is too long.
In my mind there is no need to write the artist there again because he is already shown at the top.
I removed it and for me it looks fine...

![bibliothek_org](https://cloud.githubusercontent.com/assets/10674771/7435287/b3566a04-f042-11e4-94d3-db5b5083f443.jpg)

![bibliothek_1 4](https://cloud.githubusercontent.com/assets/10674771/7435357/601454e0-f043-11e4-8122-f325e81c7772.jpg)

**Comment by MPconta** [comment]
I want to support this!
To enter the artist-library-view you have to choose the desired artist. So it is obvious, which artist you will find.
I did not evan know, that the number of songs and the total-time of the album are displayed because the artist-name is always to long. ;-)

**Comment by rompolompo** [comment]
+1

**Comment by abarisain** [comment]
Good point. I do think it's not always the same though (artist vs album artist) but I might be wrong.

**Comment by MPconta** [comment]
Big Thank You!!
It is MUCH better readable now!

**Comment by w-b-kelso** [comment]
Very nice, thank's!
