### ISSUE TITLE
HTTP Streaming doesn't work (for me?)

### ISSUE THREAD

**Issue by metaf** [abarisain/dmix#717]
I get the message below when I try to check the "streaming" box and hit play:

     MPDroid stream error: Unspecified media player error Network related operation error..

The "About" menu shows 1.07.02 Final ba27d2a-c(54).  I downloaded the APK from the releases page on github, since I couldn't get streaming working with the Play store version.  After doing so, I realized that they claimed to be the same version, but I didn't get the error message when I was trying to stream before (it just silently failed.)

I'm pretty sure my server is setup correctly, since I can control the stream from MPDroid, and I can listen to the http stream in VLC.  FWIW, I've included my MPD audio output section below:

    audio_output {
        type "httpd"
        name "mpd_httpd_host"
        encoder "lame"
        port "8000"
        bitrate "320"
        format "44100:16:1"
        max_clients "0"
    }

I don't really know much about your project yet, so pardon me if I'm not providing enough information here.

**Comment by metaf** [comment]
Hrm.  I installed 1.06-Final and then it seemed to work.  So then I installed 1.07 again just to make sure I wasn't being an idiot, and it also works there.  

I think you can probably mark this up to user error, though I'm really not sure what I did.

**Comment by avuton** [comment]
This is almost always user error. Better error handling might be nice, but, we've pretty much done all the error handling possible with this API. Anyhow, glad to hear it's working for you!

**Comment by ionsquare** [comment]
In case anyone else winds up here like me, I tried uninstalling and reinstalling a bunch of times and could not get streaming to work. All settings appeared to be correct and mpd logs were not showing any problems. I restarted my phone and then everything worked fine.
