### ISSUE TITLE
SongFragment fails to show title bar on KitKat

### ISSUE THREAD

**Issue by avuton** [abarisain/dmix#718]
On KitKat (maybe further back) the title bar never appears for albums where album art hasn't loaded. On rotation (and rotation back to vertical) it does appear. This happens on both a 2013 Moto X and Galaxy Nexus.
![screenshot_2015-05-07-18-46-00](https://cloud.githubusercontent.com/assets/396546/7529298/ea53461a-f4ea-11e4-9ba0-c525112633a1.png)

**Comment by abarisain** [comment]
Fixed
