### ISSUE TITLE
No sound during streaming

### ISSUE THREAD

**Issue by qugu** [abarisain/dmix#721]
Hello, 
I am running Android 5.1.1 on a Nexus 5 device. I suppose the streaming function in the application is made to allow playback of audio tracks streamed; alas there is no actual sound during playback. 
I have a set up MPD server back home:

```
audio_output {
        type            "httpd"
        name            "My HTTP Stream"
        bind_to_address "10.0.1.5"
        encoder         "lame"       
        port            "6601"
        quality         "5.0"                 
        format          "44100:16:1"
        max_clients     "0"
```
The application successfully connects to the server, queues the song and starts playback. I can see time ongoing during playback.
The server log has no errors, sample log since server start:
```
$ tail -f /var/log/mpd/mpd.log
Jun 04 19:35 : avahi: Service 'Music Player' successfully established.
Jun 04 19:44 : player_thread: played "01.02_High/Dafu – I choose you.mp3"
Jun 04 19:52 : player_thread: played "100-1_-_night_shift/Joan Reyes - Shakedown (Bass Kelph Remix).mp3"
Jun 04 22:14 : player_thread: played "01.02_High/Dafu – I choose you.mp3"
```
Finally, I can successfully get sound in other MPD clients.

How to reproduce:
Open MPDroid; Select artist - select song. Scroll up playback screen. From alternative menu select "Streaming".

Is that me doing something wrong, or the app is not intended for audio playback as it's secondary function?
Thank you.

**Comment by abarisain** [comment]
Hmm, sounds like a configuration issue to me. Your server config looks great

2015-06-04 23:04 GMT+02:00 Qugu <notifications@github.com>:

**Comment by hurzl** [comment]
do you have the streaming port enabled (in side menu)?

**Comment by qugu** [comment]
@hurzl 
Yes, I have. Even though I have no idea what others do (Single Mode, Consume Mode, Notification)

@abarisain 
Today I woke up and enabled the 'streaming mode' from side menu. I got an earphones icon in the toolbar and the music started playing - I can hear the sound. So this may have been some network or media scan issue.

Give me some time to check if the problem is reproduced and i'll come back with new details or confirm that this became resolved. Thanks.

**Comment by qugu** [comment]
Unable to reproduce anymore.
