### ISSUE TITLE
MPDroid Crashing when opened

### ISSUE THREAD

**Issue by KenBW2** [abarisain/dmix#729]
Since a recent update (< 3 updates ago on the beta channel) MPDroid crashes as soon as it's opened.

Clearing cache makes no difference

If I Clear Data it presents me with the connection settings page. I can successfully enter my connection details but as soon as I back out of settings it crashes instantly. It doesn't bring up the "Connecting" box that usually comes up.

My MPD server uses password authentication. The (comparatively terrible) Droid MPD Client can connect to it.

I've submitted an error report, not sure if you can see those.

Current version: 1.08 Beta 3 366de8c-c
Package Version: 57
Device: Moto G
Android Version: 4.4.4

**Comment by abarisain** [comment]
I'm aware of this one, but didn't have the time to fix it yet.

Thanks for the report.

(Apparently, a fix might be to use the local IP to connect to your server)

Closing this, since it's the same as https://github.com/abarisain/dmix/issues/722
