### ISSUE TITLE
Some problems

### ISSUE THREAD

**Issue by burmar** [abarisain/dmix#730]
Hello i had found on my Note 3 neo with android 4.4.2 and last beta version two problems..
1) when i tick, from player's view,the space under the album cover and try to show the list of the artist view... mpdroid just crash everytime.
it works perfectly if i tick "go to folder" or other voice.
2) when i want to add a song to a playlist the app just show me to create a new one and not the existing lists.
3) When i answer to a phone call, the music goes in pause correctly but, when i close the call, the music don't restart like was in the pasts releases, remains in pause.
Thanks!!

**Comment by avuton** [comment]
I can confirm 3) and I will fix this.

**Comment by avuton** [comment]
God, I hate multiple bugs in an issue.

**Comment by burmar** [comment]
Don't hate me!!! :)

**Comment by avuton** [comment]
1 is probably related to Fabric.io#330. Gonna trace this one down as well.

**Comment by avuton** [comment]
3) Fixed by 87ab84a.

**Comment by avuton** [comment]
1) wasn't what I thought it was. I need more information, I can't reproduce it.

**Comment by avuton** [comment]
2) Fixed by a259523.

**Comment by avuton** [comment]
So, @burmar I definitely need information on 1). The best thing to do would be to get us a logcat of the crash, itself.

**Comment by burmar** [comment]
I need to root my device to use a catlog... and i cannot do it :(
other ways to do it?

**Comment by avuton** [comment]
No, you don't need root, but you cannot do it with another app without
root. You can hook it up to a PC/Mac and use ADB.

On Mon, Jul 27, 2015 at 2:44 AM, burmar <notifications@github.com> wrote:

> I need to root my device to use a catlog... and i cannot do it :(
> other ways to do it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/abarisain/dmix/issues/730#issuecomment-125148286>.
>



-- 
avuton
--
Fortes fortuna adiuvat

**Comment by burmar** [comment]
Is it in the android studio bundle...? 1gb of installation software... 
There is not another android tool without rooting device?

If i'll send you the crash log throught app debugging is it useless?

![2015-07-27 15 23 56 medium](https://cloud.githubusercontent.com/assets/2404516/8910104/451e7bf8-3485-11e5-93c3-49ba2742bea4.jpg)
![2015-07-27 15 26 21 medium](https://cloud.githubusercontent.com/assets/2404516/8910105/4524a0a0-3485-11e5-87b0-57137d1e8536.jpg)

**Comment by avuton** [comment]
No, you can pick up a standalone copy of [adb](http://www.xda-developers.com/lightweight-adb-and-fastboot-installer/). If you're using Linux, it's likely in your repository. But yes, that isn't helpful to me.

**Comment by avuton** [comment]
Please reopen with the adb log requested.
