### ISSUE TITLE
Android 5: notification is not displayed on lock screen

### ISSUE THREAD

**Issue by majewsky** [abarisain/dmix#733]
In Android 5, notifications are displayed on the lock screen, but the default is for their contents to be hidden. So all I'm seeing of the MPDroid notification is "MPDroid \n Contents hidden". Other media players allow their notifications to show their contents on the lock screen, so playback can be controlled without having to unlock the phone.

Without being an Android developer, if I understand [this article here](http://www.intertech.com/Blog/android-development-tutorial-lollipop-notifications/) correctly, it should be a one-liner along the lines of `notification.setVisibility(Notification.VISIBILITY_PUBLIC);`. I hope I'm correct and this is an easy fix. :)

**Comment by abarisain** [comment]
Thanks, I'll fix this :)

**Comment by avuton** [comment]
Fixed via 5272ec9.
