### ISSUE TITLE
Help with local cover art please

### ISSUE THREAD

**Issue by richnet31** [abarisain/dmix#735]
I followed the wiki on setting up nginx and lighttpd, still no album art showing in MPDroid.
/etc/fstab has:
//192.168.2.2/music /data/remote cifs defaults username=***,password=***
/etc/mpd.conf has line:
music_directory   "/data/remote"

So, not sure if my mpd-cover-art.conf is correct:

server {
    listen 80;
    server_name 192.168.2.2;

    location /music/ {
        root /music/;
        rewrite /music/(.*) /$1 break;
        try_files $uri $uri;
        allow   192.168.2.0/24;
        deny    all;
    }
}

Thanks in advance.
-Richard

**Comment by rompolompo** [comment]
Change the following:

*root /music/;*

To the following:

*root /data/remote/;*

You need the actual path of the music folder as seen by the OS and not by
MPD.

**Comment by richnet31** [comment]
Thanks, I missed that part.  Once the folder.jpg is added to the album folder, what is needed for it to refresh and appear on MPDroid?  MPD restart?

**Comment by rompolompo** [comment]
You need to specify folder.jpg as your image under MPDroid. MPDroid will
fetch the images automatically.

**Comment by hurzl** [comment]
long press the image/dummy

**Comment by richnet31** [comment]
Thanks!
