### ISSUE TITLE
Add option to keep the screen on (e.g., when playing)

### ISSUE THREAD

**Issue by martignlo** [abarisain/dmix#737]
It would be nice to have the possibility to keep the screen on (e.g., when the music is playing and the app is in foreground). This would allow to dock the phone/tablet and build a very convenient to use docked remote. 

The screen can be kept on using other apps (e.g., tasker), but having the functionality directly in mpdroid would allow to specify finer grained conditions to control when the screen should not go off.

**Comment by abarisain** [comment]
Sorry, I think you should use another app for that, especially considering how Android allows this kind of automation.
