### ISSUE TITLE
Covers cache is not updated as a whole in Album list

### ISSUE THREAD

**Issue by rripio** [abarisain/dmix#739]
Album list only shows covers that has been directly called. The full set of covers is not fully retrieved as it used to be, or I haven't seen a way to update it.

[edited: "Album list" instead of "Album view"]

**Comment by abarisain** [comment]
Are you using local cover art rather than the 3rd party services ?

**Comment by rripio** [comment]
Ho, yes, sorry, I should have mentioned it.

2015-07-29 9:03 GMT+02:00 Arnaud Barisain-Monrose <notifications@github.com>
:

> Are you using local cover art rather than the 3rd party services ?
>
>
>
>
> > Le 29 juil. 2015 à 08:44, Roberto Ripio <notifications@github.com> a
> écrit :
> >
> > Album view only shows covers that has been directly called. The full set
> of covers is not retrieved updated as it used to be, or I haven't seen a
> way tu update it.
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/abarisain/dmix/issues/739#issuecomment-125864697>.
>



-- 
Roberto Ripio

**Comment by abarisain** [comment]
Then it is normal behaviour, sorry :) we lack metadata in the album list that alows us to find the cover. Once in the album view, we have it, so we get the cover and put it in cache.

**Comment by rripio** [comment]
But then, how is it possible that it worked in previous versions? Is that
an intended change?


2015-07-29 9:29 GMT+02:00 Arnaud Barisain-Monrose <notifications@github.com>
:

> Then it is normal behaviour, sorry :) we lack metadata in the album list
> that alows us to find the cover. Once in the album view, we have it, so we
> get the cover and put it in cache.
>
>
>
>
> > Le 29 juil. 2015 à 09:08, Roberto Ripio <notifications@github.com> a
> écrit :
> >
> > Ho, yes, sorry, I should have mentioned it.
> >
> > 2015-07-29 9:03 GMT+02:00 Arnaud Barisain-Monrose <
> notifications@github.com>
> > :
> >
> > > Are you using local cover art rather than the 3rd party services ?
> > >
> > >
> > >
> > >
> > > > Le 29 juil. 2015 à 08:44, Roberto Ripio <notifications@github.com> a
> > > écrit :
> > > >
> > > > Album view only shows covers that has been directly called. The full
> set
> > > of covers is not retrieved updated as it used to be, or I haven't seen
> a
> > > way tu update it.
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub.
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/abarisain/dmix/issues/739#issuecomment-125864697>.
> > >
> >
> >
> >
> > --
> > Roberto Ripio
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/abarisain/dmix/issues/739#issuecomment-125869181>.
>



-- 
Roberto Ripio

**Comment by rripio** [comment]
I mean, previously, sliding down the screen produced a complete retrieval
of all local covers in the database. Now I expected the same bahaviour from
the "refresh" or "update" button in the album list tab (the round arrow).

2015-07-29 9:49 GMT+02:00 Roberto Ripio <filarete@gmail.com>:

> But then, how is it possible that it worked in previous versions? Is that
> an intended change?
>
>
> 2015-07-29 9:29 GMT+02:00 Arnaud Barisain-Monrose <
> notifications@github.com>:
>
>> Then it is normal behaviour, sorry :) we lack metadata in the album list
>> that alows us to find the cover. Once in the album view, we have it, so we
>> get the cover and put it in cache.
>>
>>
>>
>>
>> > Le 29 juil. 2015 à 09:08, Roberto Ripio <notifications@github.com> a
>> écrit :
>> >
>> > Ho, yes, sorry, I should have mentioned it.
>> >
>> > 2015-07-29 9:03 GMT+02:00 Arnaud Barisain-Monrose <
>> notifications@github.com>
>> > :
>> >
>> > > Are you using local cover art rather than the 3rd party services ?
>> > >
>> > >
>> > >
>> > >
>> > > > Le 29 juil. 2015 à 08:44, Roberto Ripio <notifications@github.com>
>> a
>> > > écrit :
>> > > >
>> > > > Album view only shows covers that has been directly called. The
>> full set
>> > > of covers is not retrieved updated as it used to be, or I haven't
>> seen a
>> > > way tu update it.
>> > > >
>> > > > —
>> > > > Reply to this email directly or view it on GitHub.
>> > > >
>> > >
>> > > —
>> > > Reply to this email directly or view it on GitHub
>> > > <https://github.com/abarisain/dmix/issues/739#issuecomment-125864697
>> >.
>> > >
>> >
>> >
>> >
>> > --
>> > Roberto Ripio
>> > —
>> > Reply to this email directly or view it on GitHub.
>> >
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/abarisain/dmix/issues/739#issuecomment-125869181>.
>>
>
>
>
> --
> Roberto Ripio
>



-- 
Roberto Ripio

**Comment by abarisain** [comment]
It worked if you had some options enabled, especially the local cache. Not
much has changed here, if the metadata is not here, we can't download. If
another request we make brings the metadata, we download.

2015-07-29 9:54 GMT+02:00 Roberto Ripio <notifications@github.com>:

**Comment by rripio** [comment]
Thank you Arnaud. Now I remember that I disabled local cache due to reported crashes, and now I suddenly understand your explanation :-) 
I keep waiting for the next release, and this issue can safely be closed.
