### ISSUE TITLE
Cannot build with gradle

### ISSUE THREAD

**Issue by valir** [abarisain/dmix#740]
The project won't build with the output below. Any idea?

$ ./gradlew 

FAILURE: Build failed with an exception.

* Where:
Build file '/home/valentin/proj/mpdroid/JMPDComm/backends/android/build.gradle' line: 35

* What went wrong:
A problem occurred configuring project ':JMPDCommAndroid'.
> Could not find property 'plugin' on com.android.build.gradle.LibraryExtension_Decorated@52ecc989.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4.809 secs

**Comment by avuton** [comment]
Works perfectly here. Which branch is this?

**Comment by avuton** [comment]
Better yet, if this is not the develop branch, try that one. If not that, use git or gradle clean then retry.

**Comment by valir** [comment]
The local copy was a fresh clone. However, I opened it with Android Studio, so, in doubt, I did:

$ git clean -fd
< it removed the Android Studio files>

$./gradlew
<same error>

$ java -version
java version "1.8.0_05"
Java(TM) SE Runtime Environment (build 1.8.0_05-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.5-b02, mixed mode)

**Comment by abarisain** [comment]
I don't think you're supposed to use gradlew "naked". Did you try "gradlew assemblefossdebug" ?

**Comment by valir** [comment]
OK, I still had leftovers put in there by Android Studio. Thoroughly cleaning the directory with git reset --hard fixed my problem. Now I'm back to vim, as Android Studio seems not of big help :/
