### ISSUE TITLE
Streaming checkbox does not stay checked

### ISSUE THREAD

**Issue by aaronkmiller** [abarisain/dmix#741]
I use MPDroid solely to control an mpd instance which streams audio for output on my android, never as a "remote control" for another mpd output.

Any time I stop playback or restart MPDroid the 'Streaming' checkbox gets unchecked. To check it again I first have to start playback - during which time I'm not getting any audio output obviously.

This makes for a really clunky user experience in my use case. Ideally it would stay checked until I manually uncheck it.

Really love this software otherwise. Thanks for your hard work!

**Comment by avuton** [comment]
Streaming is not meant (and has never meant) to be persistent. There's a possibility support could be added for that in the future, but as if right now, until support has been decided to be added, the decision is not to (there are bigger fish to fry and server bugs make adding support improbable at the moment). See #599 and others. Also, see the wiki article about how streaming is meant to work, which details the lack of persistence support. Closing this for now, I'll try to leave a note if I ever add support. Thanks for the request!

**Comment by avuton** [comment]
[The Wiki Entry](https://github.com/abarisain/dmix/wiki/How-the-service-works-in-MPDroid#How_streaming_works). Also, I've, actually, already begun improvements on Streaming, but I've got to fix quite a few things before persistence can even be considered. I, actually, really hope to do this in the future, but it might be some time before it's completed (a year or two).
