### ISSUE TITLE
Long tap context menue does not work

### ISSUE THREAD

**Issue by DrVanScott** [abarisain/dmix#747]
Hi,

i am currently using 1.08 Beta 3. if i long tap on a search result, a context menue with various options appears. (Add to play list, etc.) if i select one of the options, the menue gets closed, but otherwise nothing happens.

Is there a more recent apk to check if that Problem still exists?

**Comment by avuton** [comment]
I'll take a look soon

**Comment by avuton** [comment]
Sure, try this: https://drive.google.com/file/d/0B1aD76XF-iKLa3RrVzN3eVl2RDg/view?usp=sharing

**Comment by avuton** [comment]
Please give me a very detailed report if that doesn't work. There's a possibility I've fixed it, otherwise, I need a very detailed report.

**Comment by DrVanScott** [comment]
Good news: i am not able to reproduce with the version you referenced above. (1.08 Beta 3 95efd38 - f (57) )
