### ISSUE TITLE
Disappearing "Year"-Info in the "Now-Playing"-window

### ISSUE THREAD

**Issue by MPconta** [abarisain/dmix#750]
When you look at the "Now-Playing"-window, you see in the right of the Album-Name the Year-tag. But when you turn your tablet/phone 90° the year-info disappears.
Is this wanted or a an issue?

**Comment by abarisain** [comment]
No idea, I don't use these options. (I don't even really use mpdroid anymore tbh)

**Comment by MPconta** [comment]
Oh, sorry to hear that!
Hope you are not disappointed with the progress of your software!

**Comment by avuton** [comment]
@MPconta what version? If beta I'll look into it.

**Comment by jcnoir** [comment]
I also get a similar problem with the last "develop" version.
The year was only there in landscape mode but not in portrait. (8" tablet)

**Comment by MPconta** [comment]
Version is 1.08 beta.
Thanks for caring!

**Comment by avuton** [comment]
Fixed via that commit. Thanks for the report, I would have never noticed this break.

**Comment by MPconta** [comment]
Thanks a lot avuton!
Thats what i call perfect service. :-)
