### ISSUE TITLE
Add Last-Modififed to JMPDComm API.

### ISSUE THREAD

**Issue by jcnoir** [abarisain/dmix#754]
Not directly linked to MPDroid but I need your MPD API skills to write a request like this : Give me the 5 last albums added to the MPD database ?

How would you do it ?

For now I fetch the whole song list with details but it is slow ...

Thanks !

**Comment by avuton** [comment]
There's no way to tell which were just added, just the last modified. I should be adding last modified soon, so I'm going to change this bug to that.

**Comment by jcnoir** [comment]
My concern was not about MPDroid but for a little script I use server side to make dynamic playlists.
Which MPD API function would you use to do to that without fetching the whole song list ?

**Comment by hurzl** [comment]
see my "LastMod" commits https://github.com/hurzl/dmix/commits/master

**Comment by jcnoir** [comment]
@hurzl  Thanks for the input.

**Comment by jcnoir** [comment]
@avuton It may be an interesting subject but my issue had nothing to do with Add Last-Modififed to JMPDComm API.
What do you plan to do with this function in JMPDComm ?

**Comment by avuton** [comment]
It's a longview part of listfiles support.

**Comment by jcnoir** [comment]
OK. Feel free to share your ideas (even longview).

**Comment by hurzl** [comment]
If I sort by album year, shouldn't the list indexer be switched off or show years? How?

**Comment by avuton** [comment]
Fixed what I changed this issue to, not sure there's anything else to do here.
