### ISSUE TITLE
MPD API : window usage in search requests ?

### ISSUE THREAD

**Issue by jcnoir** [abarisain/dmix#755]
Does anyone know how to use the "window" tag in search requests ?

I tried : search artist coltrane window 01:02
ACK [2@0] {search} incorrect arguments

Any idea ?

**Comment by kingosticks** [comment]
Are you building mpd from the development branch? Last time I checked there
was no actual release that included the window argument (despite it being
in the protocol docs).

**Comment by jcnoir** [comment]
I was just curious about the MPD command and its possible use in MPDroid. I tried it directly with telnet.

**Comment by abarisain** [comment]
His comment still applies :)

**Comment by jcnoir** [comment]
My bad. I thought you were speaking about the MPDroid dev branch and not the mpd dev branch.
Thanks for the input !
