### ISSUE TITLE
Empty album list

### ISSUE THREAD

**Issue by gijsstat** [abarisain/dmix#770]
Hi,

I have been trying to get around this problem but to no avail. I hope you can help me.
I have mopidy version 1.1.1 installed using the sqlite local library. In mpdroid I can see the artists, but the album tab remains empty.
When I look in mopidy's debug I see this happening:
  Request from [::ffff:192.168.179.26]:53762: list "album" "group" "artist"
DEBUG    2015-10-18 10:27:00,700 [22935:MpdSession-19] mopidy.mpd.session
  Response to [::ffff:192.168.179.26]:53762: ACK [2@0] {list} not able to parse args

Now, strangely, when I was using an older version of mopidy (0.19.x) when I was requesting the albums mpdroid would request list "album" only which worked fine. So it seems to me to be an issue on mpdroid's side, but on the other hand how can I be the only one affected?

Same happens if I use the json library by the way.

Thanks for any help!

**Comment by abarisain** [comment]
My guess is that mopidy advertises as too new and doesn't implement the latest mpd protocol features

**Comment by gijsstat** [comment]
That is a good suggestion. In the old version it reported 0.17.0, 1.1.1. reports 0.19.0.
Is there an easy fix to this in the sense that I could either change the version reported by mopidy or how mpdroid interprets this? Or can you perhaps suggest a different back-end (on raspberry pi)?

I need to use the new version because track order is a problem in the json library, and the sqlite library only reports the first couple of albums in the old version of mopidy.

**Comment by abarisain** [comment]
First of all, I suggest you take it upstream. Mopidy devs are quite reactive.  

I guess you could patch it to send 0.17.0. Mopidy is python, it will be super easy to grep your way in it and patch it

**Comment by gijsstat** [comment]
I tried and that works indeed. I have raised an issue in mopidy: https://github.com/mopidy/mopidy/issues/1314

**Comment by whumann** [comment]
To save people not knowing python and its file locations (like me) some time -- I found the line
VERSION = '0.19.0' 
that I changed to
VERSION = '0.17.0' 
in this file (on a raspberry pi):
/usr/share/pyshared/mopidy/mpd/protocol/\_\_init\_\_.py
And it helped to do so!
