### ISSUE TITLE
If i tick "Use album cache" then mpd crash

### ISSUE THREAD

**Issue by burmar** [abarisain/dmix#775]
Time ago i started an issue about this problem:
On my Note 3 neo with android 4.4.2 and last beta4 version, when i tick, from player's view, the space under the album cover and i try to select the "go to artist", mpdroid just returned an error message really difficult to capture, this message pop up only at the first time, then every other tick returns an empty result window from the query.

it works perfectly if i tick "go to folder" or other voice.

![2015-11-05 19 55 55 small](https://cloud.githubusercontent.com/assets/2404516/10980217/1f622b0a-8401-11e5-8021-7443912c9661.jpg)

Today i had finally found where is starting the problem...
if i tick "Use album cache" then mpdroid crash.. if i untick it then the app works flawlessly...

![2015-11-05 16 30 54](https://cloud.githubusercontent.com/assets/2404516/10980401/1dad0c66-8402-11e5-909a-4ab115b670ba.jpg)

that's all

Thanks for this great app and keep it alive!! :)

**Comment by hurzl** [comment]
A log, if possible, would be great

**Comment by burmar** [comment]
My phone is not rooted and i tried once to log.. but doesn't work
or maybe was my fault...

**Comment by avuton** [comment]
Please reopen when you have a log.
