### ISSUE TITLE
NowPlaying now always light theme?

### ISSUE THREAD

**Issue by hurzl** [abarisain/dmix#778]

**Comment by abarisain** [comment]
Definitely not intended, but you're the first to report that

**Comment by hurzl** [comment]
71b254d102ad2dcb9a0f5003f237c50eeb121ff5

**Comment by avuton** [comment]
Interesting. Works as intended here. I'll take a look sometime.

**Comment by avuton** [comment]
Terrible issue, no description. If you are not testing on abarisain, test on that. I cannot duplicate. I've tried all sorts of ways.

**Comment by hurzl** [comment]
Waht do you mean by "testing on abarisain"? It's on the develop branch. Only NowPlaying is light theme.

**Comment by avuton** [comment]
What happens when you select the other theme?

**Comment by hurzl** [comment]
It changes. Only NowPlying doesnt: I changed back and forth
The buttons are mixed black and white

**Comment by hurzl** [comment]
The Queuelist is light too, despite Tools.isLightThemeSelected() always returns false

**Comment by avuton** [comment]
OK, I need to know why there's a problem. I'm interested in fixing this problem, but it doesn't occur on either my Nexus 6 or my Nexus 10. I mean, cleared data or anything this just doesn't occur. The theme always switches just as it should. You're saying that "isLightThemeSelected()" always returns false, which tells me it's /not/ taking the 'true' default, which means when you change the theme, for some reason, the change is not setting in the shared default preferences. That's all I really know, and I can't tell you why that wouldn't happen. As far as the frequency of the call, that's an old problem, nothing that's changed lately.

You could add some debug code to SettingsFragment:176, something like:
Log.d(TAG, "Pref " + preference.getKey() + " changed to " + newValue.toString()); and make sure the change is occurring. If so, then, you could work your way from there. I don't have an emulator, I'd check there, but this is working perfectly here.

**Comment by hurzl** [comment]
I mean it's not returning false when I set lightTheme, I only say it returns false which is what I want ans settings seem to work ok, but NowPlaying is light nevertheless.

**Comment by hurzl** [comment]
What's happening in that commit? Can it be split up?

**Comment by avuton** [comment]
Lots going on in that commit. First, we move some things to a common ```AppCompatActivity```, extend the Activities to use that, move isLightThemeSelected() from MPDApplication to tools and use context to resolve the preferences parameter, change the warning activity stuff to reroute,

**Comment by avuton** [comment]
That reply went early, but doesn't matter. Do you have small seekbars enabled or disabled?

**Comment by hurzl** [comment]
I think not, but now this setting is disabled?

**Comment by hurzl** [comment]
Error: MPDActivity returns the light theme id on getThemeResId() and this is called by NowPlayingActivity.getThemeResId() if small seekbars are not enabled.

**Comment by hurzl** [comment]
it should look like this:

```
    @Override
    protected int getThemeResId() {
        final SharedPreferences settings = PreferenceManager.getDefaultSharedPreferences(this);
        final int themeID;

        if (settings.getBoolean("smallSeekbars", true)) {
            if (isLightThemeSelected()) {
                themeID = R.style.AppTheme_Light_SmallSeekBars;
            } else {
                themeID = R.style.AppTheme_SmallSeekBars;
            }
        } else {
            if (isLightThemeSelected()) {
                themeID = R.style.AppTheme_Light;
            } else {
                themeID = R.style.AppTheme;
            }
        }

        return themeID;
    }
```

**Comment by hurzl** [comment]
probably it should be done in MPDActivity

**Comment by avuton** [comment]
Yeah, think I was slightly off on the logic for the override. I'll take another look tomorrow.

**Comment by avuton** [comment]
I don't have a pre-lollipop device, testing this would be appreciated.

**Comment by abarisain** [comment]
Does it matter though?

**Comment by avuton** [comment]
Small seekbars are only supported pre-lollipop according to the comments.

**Comment by abarisain** [comment]
Oh right. I'm not even sure of this anymore :p

**Comment by avuton** [comment]
Yeah, I have no idea, f85297c.

**Comment by abarisain** [comment]
I'll have to check it out :)

**Comment by avuton** [comment]
OK, so, no testing, huh? OK, I'll push it out sooner than later.

**Comment by abarisain** [comment]
It'll get tested, I don't worry about that :)

**Comment by hurzl** [comment]
:+1:
