### ISSUE TITLE
Compilation albums split by artist in library

### ISSUE THREAD

**Issue by nawcom** [abarisain/dmix#782]
I have a ton of compilation / Various Artists albums in my library, and I noticed that unlike other MPD clients, MPDroid still splits up the albums by the different artists in the Album list. So an album with, let's say 20 tracks with a different artist in each track will show the album 20 times under Albums. Is there a way to get it to show just one single icon for the Album? It just seems that the Album list still pays attention to the artist name when listing them which I find strange. Isn't that what the Artist list is for? Other MPD clients don't have this issue.

For these MP3s/FLACs, I have Artist set to the given artist name and for Album Artist I have "Various Artists"

**Comment by nawcom** [comment]
I just set the Album Artist to every song to "Various" and that seemed to do the job. Definitely makes the album list shorter now.

**Comment by abarisain** [comment]
So something changes from "Various Artists" -> "various" ?
