### ISSUE TITLE
Streaming not working

### ISSUE THREAD

**Issue by basedheaven** [abarisain/dmix#789]
I can control the playback on my computer but I cannot stream

mpd.conf

music_directory "~/Music/"
playlist_directory "~/Music/"
db_file "~/.mpd/mpd.db"
log_file "~/.mpd/mpd.log"
pid_file "~/.mpd/mpd.pid"
state_file "~/.mpd/mpdstate"
audio_output {
        type "pulse"
        name "pulse audio"
}
audio_output {
    type                    "fifo"
     name                    "my_fifo"
    path                    "/tmp/mpd.fifo"
    format                  "44100:16:2"
}
audio_output {
    type        "httpd"
    name        "My HTTP Stream"
    encoder        "vorbis"        # optional, vorbis or lame
    port        "8002"
\#    quality        "5.0"            # do not define if bitrate is defined
    bitrate        "128"            # do not define if quality is defined
    format        "44100:16:1"
}
bind_to_address "192.168.0.13"
bind_to_address "localhost"
port "6601"

And settings on phone

Outputs: all selected

Connection settings
Host: 192.168.0.13
Port: 6601
Password: blank
Streaming Host: 192.168.0.13
Streaming port 8002
Streaming url suffix: blank
Persistent notification: unchecked

I know I must be missing something basic but I've been trying for hours and no luck.

**Comment by hurzl** [comment]
Not working for me any more, too :(
I get a toast about an unspecified network error

**Comment by avuton** [comment]
Nothing's really changed here (I still use it daily), but, I need much more information. The unspecified network error should have more if someone has a logcat. @basedheaven What version?

**Comment by hurzl** [comment]
```
D/MediaHTTPConnection(10991): filterOutInternalHeaders: key=User-Agent, val= stagefright/1.2 (Linux;Android 5.1.1)
D/MediaHTTPConnection(10991): proxy null port 0
E/IMediaHTTPConnection(  202): requested 65536, got 4294967295
E/NuCachedSource2(  202): source returned error -1008, 8 retries left
D/MediaHTTPConnection(10991): filterOutInternalHeaders: key=User-Agent, val= stagefright/1.2 (Linux;Android 5.1.1)
D/MediaHTTPConnection(10991): proxy null port 0
E/IMediaHTTPConnection(  202): requested 65536, got 4294967295
E/NuCachedSource2(  202): source returned error -1008, 7 retries left
D/MediaHTTPConnection(10991): filterOutInternalHeaders: key=User-Agent, val= stagefright/1.2 (Linux;Android 5.1.1)
D/MediaHTTPConnection(10991): proxy null port 0
E/IMediaHTTPConnection(  202): requested 65536, got 4294967295
E/NuCachedSource2(  202): source returned error -1008, 6 retries left
D/MediaHTTPConnection(10991): filterOutInternalHeaders: key=User-Agent, val= stagefright/1.2 (Linux;Android 5.1.1)
D/MediaHTTPConnection(10991): proxy null port 0
E/IMediaHTTPConnection(  202): requested 65536, got 4294967295
E/NuCachedSource2(  202): source returned error -1008, 5 retries left
W/art     (11296): Suspending all threads took: 9.827ms
D/MediaHTTPConnection(10991): filterOutInternalHeaders: key=User-Agent, val= stagefright/1.2 (Linux;Android 5.1.1)
D/MediaHTTPConnection(10991): proxy null port 0
E/IMediaHTTPConnection(  202): requested 65536, got 4294967295
E/NuCachedSource2(  202): source returned error -1008, 4 retries left
D/MediaHTTPConnection(10991): filterOutInternalHeaders: key=User-Agent, val= stagefright/1.2 (Linux;Android 5.1.1)
D/MediaHTTPConnection(10991): proxy null port 0
E/IMediaHTTPConnection(  202): requested 65536, got 4294967295
E/NuCachedSource2(  202): source returned error -1008, 3 retries left
D/MediaHTTPConnection(10991): filterOutInternalHeaders: key=User-Agent, val= stagefright/1.2 (Linux;Android 5.1.1)
D/MediaHTTPConnection(10991): proxy null port 0
E/IMediaHTTPConnection(  202): requested 65536, got 4294967295
E/NuCachedSource2(  202): source returned error -1008, 2 retries left
D/MediaHTTPConnection(10991): filterOutInternalHeaders: key=User-Agent, val= stagefright/1.2 (Linux;Android 5.1.1)
D/MediaHTTPConnection(10991): proxy null port 0
E/IMediaHTTPConnection(  202): requested 65536, got 4294967295
E/NuCachedSource2(  202): source returned error -1008, 1 retries left
W/ProcessCpuTracker(  741): Skipping unknown process pid 7182
W/ProcessCpuTracker(  741): Skipping unknown process pid 7185
W/ProcessCpuTracker(  741): Skipping unknown process pid 7187
W/ProcessCpuTracker(  741): Skipping unknown process pid 7200
D/MediaHTTPConnection(10991): filterOutInternalHeaders: key=User-Agent, val= stagefright/1.2 (Linux;Android 5.1.1)
D/MediaHTTPConnection(10991): proxy null port 0
E/IMediaHTTPConnection(  202): requested 65536, got 4294967295
E/NuCachedSource2(  202): source returned error -1008, 0 retries left
D/MediaHTTPConnection(10991): proxy null port 0
I/FFmpegExtractor(  202): android-source:0xb5871390
E/FFmpegExtractor(  202): android-source:0xb5871390: avformat_open_input failed, err:Unknown error 1008
W/FFmpegExtractor(  202): sniff through BetterSniffFFMPEG failed, try LegacySniffFFMPEG
E/FFmpegExtractor(  202): android-source:0xb5871390|file:http://192.168.0.10:8002: avformat_open_input failed, err:Unknown error 1008
D/FFmpegExtractor(  202): SniffFFMPEG failed to sniff this source
E/GenericSource(  202): Failed to init from data source!
E/MediaPlayer(10991): error (1, -2147483648)
E/MediaPlayer(10991): Error (1,-2147483648)
E/StreamHandler(10991): Nicht spezifizierter Fehler vom Mediaplayer. Netzwerk bezogener Ablauffehler.
D/NuPlayerDriver(  202): reset(0xb4c37640)
D/NuPlayerDriver(  202): notifyResetComplete(0xb4c37640)
D/MPDroidService(10991): Received message: StreamHandler.STREAMING_STOP

```

**Comment by basedheaven** [comment]
Mpdroid 1.07.2

**Comment by avuton** [comment]
@hurzl Would you mind bisecting? Also, are you using the built in MPD streaming server?

**Comment by hurzl** [comment]
I really wouldn't know where to start ...
Which built in server? Are there alternatives?

**Comment by hurzl** [comment]
I get exactly the same errors when calling the stream from mx player. So it seems to be an android problem.

**Comment by avuton** [comment]
@basedheaven humor me and try lame rather than vorbis.

**Comment by abarisain** [comment]
That's "fun", especially when I remember that back in the 2.x days, vorbis was the only option before 2.2

**Comment by avuton** [comment]
Yeah, not really sure what's going on here, but streaming is difficult to support.. It's not that the code isn't bulletproof (it is). It's more that we can't tell the user what's messed up. Also, I've noticed vorbis screw things up on some devices/versions.

**Comment by abarisain** [comment]
Historically, MediaPlayer has always been a buggy mess. Custom ROMs love breaking it too.

You of all people know what I'm talking about. Bonus points for the API not giving any error reporting at all.

**Comment by avuton** [comment]
I know... Seriously makes me consider building a library  check links for a valid stream. I don't have time for that, but it's be nice if someone did. :)

**Comment by avuton** [comment]
@basedheaven guess that fixed it?

**Comment by traaf** [comment]
same here.
@avuton suggestion did the job. using lame instead of vorbis to enable the sound on smartphone.
would be a good idea to change the default vorbis parameter to lame

**Comment by hurzl** [comment]
I was just confusing IP adresses, everything works ... ;} 
Maybe there should be an error that says "no such port on that machine"?
