### ISSUE TITLE
Slow caching

### ISSUE THREAD

**Issue by Phyks** [abarisain/dmix#791]
Hi,

I am using MPDroid to stream music from my MPD server to my phone, but am having some issues with caching, on the same Wifi network (stream is 128kbps OGG).

Caching is really slow (it takes almost a minute of caching before the song actually starts). And then, there is a big latency between the output sound and the music controls (30s to 1 min).

If I go to the stream URL on my laptop (same Wifi network), the latency is only 2-3s, which is much more reasonable.

Thanks

**Comment by abarisain** [comment]
Thanks for the report.

Sadly, we can't do much about this, since we have no control of how Android's media player handles this.

**Comment by avuton** [comment]
Yeah, we purposefully slow down the stream on [old versions](https://github.com/abarisain/dmix/blob/develop/MPDroid/src/main/java/com/namelessdev/mpdroid/service/StreamHandler.java#L280) of Android, but only for 1.5 seconds. That's the only control we have over stream caching, sorry. From there, it's Android which controls the stream (MediaPlayer specifically).

**Comment by Phyks** [comment]
Ok. Are there some streaming setups that are known to work best (e.g. using MP3 vs OGG or something like this)?

**Comment by avuton** [comment]
I wish I could tell you. There will be lag, but the greatest lag I've ever seen has been less than 10s. I would tool around with it a bit, but you're unlikely to change things in a way that has a meaningful effect. Are you using some custom rom or something?

**Comment by Phyks** [comment]
Nope, am using standard AOSP 4.2 on a Fairphone FP1.

**Comment by avuton** [comment]
Yeah, I hope you find the problem, but it is, unfortunately, not in MPDroid. Because of the version, there is a 1.5 second delay that we have to add, which decreases the likelihood of a known bug in AOSP 4.2, but otherwise, we're simply using the MediaPlayer code built into your Android. You could try switching MP3 to OGG or visa versa. Who knows? Could fix things.

**Comment by Phyks** [comment]
Ok, I will try it. Thanks for your help! :)
