### ISSUE TITLE
Sort by album artist

### ISSUE THREAD

**Issue by Chais** [abarisain/dmix#795]
Personally I'd love to have the option to sort by 'album artist' tags. I tag my music like this:

* Album Artist = Artist of the whole album (e.g. KoRn)
* Artist = Artist of the specific track (e.g. KoRn feat. Skrillex)
* Title = Track name (e.g. Narcissistic Cannibal)

Currently I have to resort to going through the file hierarchy, because sorting by Artist regularly rips albums apart.

**Comment by abarisain** [comment]
Don't we have that already?

**Comment by Chais** [comment]
I'm offered Artists, Albums, Playlists, Streams, Files and Genres in the dropdown menu. Sorting by Album leaves the albums intact, but sorts them alphabetically by name and overall is rather impractical for large libraries.

**Comment by abarisain** [comment]
There should be an option in the library settings

**Comment by Chais** [comment]
Oooh. Yes, after trying all the settings I found it. The description diddn't immedeately give it away. Thanks a lot.
