### ISSUE TITLE
client fails to connect, "output buffer is full" error on server

### ISSUE THREAD

**Issue by anarcat** [abarisain/dmix#806]
i had managed to setup mpdroid correctly here at some point. yet now, for a reason I can't figure out, it's totally failing to start.

on the mpd server, I see:

```
Apr 11 11:21 : client: [32] opened from 192.168.0.117:51334
Apr 11 11:21 : buffered_socket: error on client 32: Output buffer is full
Apr 11 11:21 : client: [32] closed
```

... many times per second, until I quite the mpdroid app.

on the client side, I see:

![Connection Failed! error](https://cloud.githubusercontent.com/assets/796623/14432326/a53163c0-ffd7-11e5-8b29-6badd3333a8a.png)

Sometimes, it actually works and i *can* use it for a while. but all of it is pretty unreliable... doing 'retry' just fails, and the only solution is to quit the app.

**Comment by jcnoir** [comment]
Try to increase the output buffer in your mpd server configuration (mpd.conf) : max_output_buffer_size "8192" ==>  max_output_buffer_size "32768" then restart your server.

**Comment by anarcat** [comment]
that seems to have fixed the problem. thanks.
