### ISSUE TITLE
MPDroid cannot resolve hostname

### ISSUE THREAD

**Issue by fooness** [abarisain/dmix#815]
Can someone explain this behaviour?

Back in the days, when I was using a fritz router, MPDroid could connect to my MPD server just via "hostname" (no hostname.fritz.box, no hostname.local).

Now on my new router the domain would be .local, though MPDroid can only connect to the MPD server via the IP (which changes due to DHCP) and I’d like to get this working again.

From my laptop’s command line I can access the MPD server host via hostname.local … why not from my smartphone? I tried clearing the cache, deleting the settings and reinstalling the app.

Thank you!

**Comment by abarisain** [comment]
Can you try to run a local shell on your phone and resolve this? Looks like your phone is not picking up on the avahi broadcasts, which hapoens often.

Not closing this yet, but If it used to work before you changed your conf, I doubt it is an MPDroid proboem. Mpdroid uses the system's hostname resolver, and does not try to do anything fancy

**Comment by fooness** [comment]
Thank you! A ping from my phone also does not work. How can I fix the often happening behavior you described above?

**Comment by abarisain** [comment]
Sorry, but I don't really know how to fix this, I gave up :D

Closing this since it is unrelated to mpdroid
