### ISSUE TITLE
Streaming checkbox nowhere to be found

### ISSUE THREAD

**Issue by mdlayher** [abarisain/dmix#819]
I've read a few times that there is a "streaming checkbox" somewhere, but I can't for the life of me find it in the application.

I have everything configured correctly as far as I can tell.  I'm using LAME after hearing there are issues with Vorbis streams.  VLC is able to open the stream just fine.  I've configured MPDroid with the same settings, but as far as I can tell, there is no way to actually enable streaming.

The only thing I'm doing differently that I can tell is binding the HTTP streaming output to a different port (6601, instead of 8000).

MPDroid version is `1.07.2 Final ba27d2a-c (54)`.

Am I missing something obvious?  Thanks for your time.

**Comment by abarisain** [comment]
Hi!

It should be in the now playing activity. Press the overflow menu button and you should see it

**Comment by mdlayher** [comment]
Thanks a ton.  For some reason, I hadn't bothered to check there.  My apologies!
