### ISSUE TITLE
TIMER Function

### ISSUE THREAD

**Issue by ch0senfew** [abarisain/dmix#820]
mpdroid is a great app which I use with my raspi.
But there's one thing I'd been rather missing.
Would appreciate a timer function to have the possibility to stop MPDroid after a specific time.

**Comment by flan** [comment]
Seconded. I don't know how doable this is, but this would be great to have.

**Comment by abarisain** [comment]
Hello!

This is a frequent request, but I don't think we will able to satisfy it for two reasons.

The first being that this should really be done on the server side. Android can lose connection easily, while the server will always be able to honour your sleep request.

The second is that mpdroid isn't really under active development anymore
