### ISSUE TITLE
Streaming is out of sync with server/visualizer

### ISSUE THREAD

**Issue by BlitzKraft** [abarisain/dmix#829]
When I start streaming, there is about a 10 second delay, which is fine. But the visualizer in mpd is now 10 secs ahead of what's playing. 

Is this expected behaviour? How can I reduce the delay? Or is there a way to set the server to skip ahead the time when I begin streaming?

**Comment by grandchild** [comment]
This is expected. HTTP streaming creates a separate audio buffer of about half a second at least (and often more, to prevent skipping). Add to that network delay (probably on the order of a few hundred milliseconds) which can be noticable, and you have a situation where the audio on your phone is constantly a few seconds off. That is the nature of digital audio — buffers.

So there is no way to have server and stream output in sync, unless the server somehow knows how much delay the stream has on the receiver. You could think of solutions, but the complexities here are considerable (HTTP audio streams have no back-channel, multiple stream receivers with individual delays, etc.), and would need coordination on mpd server and client projects. I wouldn't hold my breath...

**Comment by BlitzKraft** [comment]
Ah. Good to know. Thank you for the detailed response. Closing.
