### ISSUE TITLE
Streaming function completely broken, or is it just me?

### ISSUE THREAD

**Issue by adolfintel** [abarisain/dmix#846]
I'm trying to use MPDroid to stream music from home to my mobile device, and since this is the only player that supports this on Android, I set it up and gave it a try.
Controlling MPD works perfectly, but my god that streaming function is broken:
* Streaming doesn't start automatically
* Streaming sometimes disables itself for no apparent reason and needs to be turned on again
* Streaming sometimes doesn't start at all, you turn it on and nothing happens, and the app needs to be restarted
* Moving to a different network/cell makes the stream stop, no automatic reconnection
* The buffer is INSANELY big, changing a song takes like 10-15 seconds

Is this a problem with Android 7, or this application?

**Comment by abarisain** [comment]
That's all Application problems.

It uses the old MediaPlayer API, which isn't great. So yeah, drops, has huge buffers, etc...  

The rest are purely mpdroid bugs. To be honest, the streaming code comes all the way back from 2009 and worked on Android 2.1, so it's bad.

**Comment by nachoparker** [comment]
I suggest you use the VLC app to stream your music. You can control reproduction from MPDroid.

It's a workaround, but it works

**Comment by abarisain** [comment]
Yes, this is the best solution :)

**Comment by adolfintel** [comment]
Holy shit :(
