### ISSUE TITLE
Play Store Data Safety Section

### ISSUE THREAD

**Issue by vaibhavantil1** [abarisain/dmix#878]
Hi Team

In the recent Play Store policy, it will become mandatory for you to fill out the Data Safety Section. Since this is an OSS Android app, it will make sense to have it as a part of the repository as well.

I have run the scan using [my tool here](https://github.com/Privado-Inc/privado) on your repo, attached are the scan results. I found the following:

- 3 data types
- 0 SDK

If this is helpful, do use our free tool to generate Play Store Data Safety report: https://github.com/Privado-Inc/privado

Also, do share your feedback & thanks for the OSS app 😄
![image](https://user-images.githubusercontent.com/87804852/157204715-2f00708c-093b-410b-b20c-ec0cb8c0c138.png)
![image](https://user-images.githubusercontent.com/87804852/157204826-416bce45-1f22-4eb7-a296-90a3e6ff70f2.png)

**Comment by abarisain** [comment]
Spamming your product using GitHub issues? That's new!

**Comment by vaibhavantil1** [comment]
@abarisain - Apologies if this looked like spam.
